### ISSUE TITLE
What is the 'Environment.buildTypeRelease'?

### ISSUE THREAD

**Issue by ibcylon** [AlexRoar/TuistExample#1]
```swift
// Project+Env.swift
Environment.buildTypeRelease.getBoolean(default: false) ? .release : .debug
```
Hi I'm a beginner of uFeatures
I couldn't find 'buildTypeRelease' in the repo
What is it?

Thank you

**Comment by alexdremov** [comment]
> ```swift
> // Project+Env.swift
> Environment.buildTypeRelease.getBoolean(default: false) ? .release : .debug
> ```
> 
> Hi I'm a beginner of uFeatures I couldn't find 'buildTypeRelease' in the repo What is it?
> 
> Thank you

Hi!

In my example, this option can be set by environment variable `TUIST_BUILD_TYPE_RELEASE=TRUE` during build. It affects modules packaging type

https://github.com/alexdremov/TuistExample/blob/5ee03d9ba2e959146be786789f3bac22d50b86ab/Tuist/ProjectDescriptionHelpers/Project%2BEnv.swift#L12-L14

Used here:

https://github.com/alexdremov/TuistExample/blob/5ee03d9ba2e959146be786789f3bac22d50b86ab/Tuist/ProjectDescriptionHelpers/Project%2BTemplates.swift#L27-L42
